### ISSUE TITLE
Unknown dependency CommandFramework:3.1.7

### ISSUE THREAD

**Issue by MerryDev** [QuantraxNET/CityBuild-Gradle#19]
Although the required repos and dependencies were added to the buildscript file, IntlliJ was unable to load them into the classpath.

![image](https://github.com/QuantraxNET/CityBuild-Gradle/assets/56554514/608ab055-4759-4b37-8e7c-10f6360ed006)
![image](https://github.com/QuantraxNET/CityBuild-Gradle/assets/56554514/bf5af98c-701b-44d9-a0e4-17b5fd8b667c)
![image](https://github.com/QuantraxNET/CityBuild-Gradle/assets/56554514/d5093dbe-774a-403d-99e3-3ad0c2b77525)

**Comment by Knerio** [comment]
Fehler gefunden: Mein Repo Server macht Probleme, bin am fixen

**Comment by Knerio** [comment]
Resolved when merged: https://github.com/QuantraxNET/CityBuild-Gradle/pull/20
